apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-custom-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stanleycprime/kyverno-policies.git
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
